//
//  FindK-LengthSubstringsWithNoRepeatedCharacters.swift
//  leetcode
//
//  Created by MickyZhu on 6/2/2020.
//  Copyright © 2020 Henry. All rights reserved.
//

import Foundation

class FindK_LengthSubstringsWithNoRepeatedCharactersSolution {
    func numKLenSubstrNoRepeats(_ S: String, _ K: Int) -> Int {
        let chars = Array(S)
        if chars.count < K || K == 0 {
            return 0
        }
        if K == 1 {
            return chars.count
        }
        
        var res = 0
        var map = [Character: Int]()
        var i = 0
        map[chars[i]] = i
        var j = 1
        while j < S.count {
            let c = chars[j]
            if let index = map[c] {
                if j-index == K {
                    res += 1
                }
                
                for k in i...index {
                    map.removeValue(forKey: chars[k])
                }
                map[c] = j
                i = index+1
            } else {
                map[c] = j
                if map.count == K {
                    res += 1
                } else if map.count > K {
                    map.removeValue(forKey: chars[i])
                    i += 1
                    res += 1
                }
            }
            
            j += 1
        }
        
        return res
    }
    
    func test() -> Void {
        print(numKLenSubstrNoRepeats("havefunonleetcode", 5))
        print(numKLenSubstrNoRepeats("home", 5))
        print(numKLenSubstrNoRepeats("bgfikghkcebcabhkdghlgkhhcbjdjfclgfafhibikbedbfdkifejahcadehlhilegcacgcjijeklihcf", 5))
        print(numKLenSubstrNoRepeats("fqezicakyohxbsbivjjglqrehiwpkcfdpxcjzwlmqqodnkarcedxqbdjhlbwqqcnykvyzvpaivzxyhasjsnlevolsvrnyvgkhturklmzqfhvjbeqhykuhacznphwwjpqgmcrunmpxjeqvkkllwcdhzhrbnbkomzptavjhxvhvohvueurpadgwroffoittvrtpielprkytusndrhbojcvrcfxkxvlvwrsqskibucyctgmevxnvkvluyupqytbygjonxjkllupjwmrxyqaqxcxpmovqxwqglljkyqwjwebmozigszwgkzhignpxphathukvbqodntqsxeionmtqsbnfcvrqdrzcvgrraatzxstpahdpfpxpuvylfirxfwsxwhdaereeghvvgygtpftezegkkrdxahloeagrgruebyymvksghypqpktqptxwedkpflpkcgstpsfbgkymdsiosgynqdqashsquuwitldtdqzonnzyqtlmzlppolwxjjzgrmwuonccamgbcsamfdozpjpyvqmoxfinonuqvxipbabhvxukwkgwmfkdersfeyrbcfmrgskczeojqlyqhgqemgtensfrducoetocaufhfqafxrluekuwxhkparpmtbkwuvocweywasdbjdpcebiuryaoyvuywfxumvssckjhgsysbpposaonqdydexeglttivxenurzhctnsxapdcficrintkemmpypqpaiwxskmibqtxgutuaxgbswumhfxutqaykvvmtfugpburtosrhcgkniohhxzgyvmxhktahonjvctllqtcyxcwbkdzbkroidyvytbrjwlubvrfqyarifpjrndbrbivocjaddrxopwhhaswssnernghkyxlfrapwnnytvulexgerxxcnjcxrxaubtdxauopzuccmjigshyosvjmdlbtlwczyzgsuwvdsmofawjrfgwnlsutomijjsefiwvqwtqonmrddalkhdklmbdraphrsffmuvlmoqevdtighvspdtbrborbrnobwikkacmhodyutbvtllhherlqgkjmkfswfpuzxyfbzgadmxmwjaghcyekjxqkdotyehqvgfaqzyjhmyrjylypimohfqbdiyztjidywbscchqtbhmbwmaxjllemctsywpowyqxzdsyemulvbfgllrwaepzxtucoobmzdtmfeablzuwpjxuucehficqevlrenfvgbnufrldociufigzpsjccmsdjwntprjhebfojbggmfpyfjqhszpmnosqneqpgdvnwvnuhljaaamxulxmhdhudvxysndscpfahaurfucmllcbzzhzrmwsimyaebauagbajszvaezbwssjpqfokcfogcbtjediqqqvorxuxpifihxthlftacotelfgjozlcmuekqryleiaakxhbvdociuejpitjyzfjxflojalughleuzdlslasfhxsrsaqnhzhymqbfzxlihdonchmjtmyubjsepawtarggkaipqbjeswlsvzzeustpymvtvvdvtpimnybncosxrkzvxwncifrpczvfzffmtjodekcoyrrfojebalblvrshcvzurhckhndsnqddlofszihwtyvanavpicwoqpzuofgigefygryjksgxtreeghyzrjfcbtswugpbmvevrlrwhjlzfaxqxzbdoizddzhimvdoveiozedhaljqudaqeoozvdmmgxvaayjtuniljxhlfnygeewidmgjxjvbnniietnzwumtmfhftgmdiqwdeofjhpxdqhrkueqmmayjnasmsegpfqgyredygrsaasmqqjixngjlshvzejuoywrtgwjvlmybwtpotiekzrreqqmgghkscyyucjjcntuwwzfebwyydokrwkarsbvvrifkbwmknqsehtumqfevzsjafpptbkrtcutwlzelpickyggysgqmvxqkaiqwoyahlepfmwjccfwnlmbbocjojmfltqwktnyyufpfqpblptqiwuxtybksyzqvjpqaeweirxsfmlihluomoojnzmftqsktxmrimvlswrrjufdkxkoukqcrkanclzjtslrdnqqoekmoezcizhibordqirhenpdklupgxyxkpgmsglepuchuljwwztzhwtzerqjkeohlkwwgwiplxqhtxlbiwfkjcdzldagjkwxnuzvjwnlckucfjoypdqptxkdrdnvtxmbjtfjevujmcubktfyvecdnguwisdavwzdtwqsotbhtpajpizuyopajzlytxgqwhxlbftsgawxvmkgmnrdswghawwzygdaxxprhwmapfmlydpdqifzxuevuidgggzdbbmsxigqyfegpdgllzxybtpoultffmdpccfozmqoiaecmtcrwbrcssmtxmnyfpbpcwxuhgijvbmdefsxlmzepqaxoajhxqboultkyxdovmxyrkqijarcxmjckhjpliqghgnwigzuxxwfczytjrnochqzkjhbskzecifrscbuhjtgnruyqlwxflxxjtqgbuupvevzckemjiygtnxuxgclztsaszqyofpdtljubvcxidtrvtichcveqsfpentvqsffqbvyrdzyglzzzuavfcavfjypgfltgqfucdbajfwhcgrhnnjtmmbwohzhbfmdiahwazomowewjwrfjtjyhmmrrijfoncuwgmucriswvbgiirzdthjsfxxsppwgsgdcjxvyinbyfenyoxtvsklismadpvjnewvqoqszadxryspwsksbpzzrbfkyvpaylgvrszpkllqdjjarovedckokzthhehsbbbaiifiynafgahscaudbqzkdkydcadqbmvpjeffyuusyltdasqeokjcniktpmdyotujlttrscotfsqlopjhosdlzszwowmnrumodauixxspsjooxljrsjnhucwefeuubzvurspovqcmgfuizwbcajhleeapigsdhsbykgoixdtidikdfyrgdgggvkxzrcrvwbcokijruuaroxbfvdctdflegwocoxtpzqtngbhmznjeyjqucegfqvpcmazfkhxhfyrpernaomazrunfcdjtvcizxeedjzgqtzrwpwtlskyokjtfcoqnyvcdrlaioyenwdsllmubilnczzsqypocorgddtfawgnkjmbzmfaxfdxfwhajwypsttbiwcaphkyczcizewjfpkvjdiogflpvdexkxamngnaammqqjhzvkgixffzqrhzcergaicfneunhzarzxlkrfqudqzdakkxdjoktcyfdxklgierjupoejgpldmhpvcyeymburyoltuzxempthhdpfcsuuratzgabeslrawxainsmbuzqmqhfuajkndobqhjnjhzzfslaojskknceewqwkiejbkuekpcebeklztybyfuisnahbblpblqqmlwggjeiyckvxbyqbgbnofhvzzinizolpgsmkjhydthowpjlvpzqosnzjiagkkkckcczyzramulfqhsqjfrxazsejdojoiwanbsofsjqcmwyjfkcqilyfkrhewyhelfegturbubrkdcalrvtqrdowspwvyqilfbboftafukhcnwoqexladxvfvntsixdmnjgffigdtmkqpuuxxhbcfhzmsowxpelifjsqtjfhqnhqtlhdusreijysysiumkydrtyokazqsysqmcuphofbympmbthhrnpgbqprhzmgflnwpnyeudgdovnlqaxypjdvdtlnusjrqremknbphbcpvsttitprznaracciznteltwmiftozbbtcjtxxchkecljihmxbrrwcerqavzecijzqqgvjbhjfsrihvprchpanzlrrjtbeytbdzzwbfodulzpxssrahshmjjiwkdpjppnmuomivmlofiokeesxfrnuatdkjxbigphcokgydtjeawutcmmuxebxgxxqyzfvpiaunktyucarkfxipyvjhsrnzqrapxdbawmveyyignaocmkxhybxvcwezwxjpjojcruqmnmnpcrlwowqywfdewriclgavtjgcomnlkyxodmddwavhvpkmnpiyuoqxvfnmdqryxrnutnievwpucesaeayczbwihpgualfivgsnezqjjdvpaaodiduuelujjisbopezbambwctdemjoregvdbsqcorivbpojbvbyybpoyhplaatlcunnfujjwyxhqltxaufopqnitbhnwxewgcsuoxznrghnyysoqwinvlxkvfldvatqkocrrlqtlkjspzurjquthrmtegasxkgayxncmjuteyjswmdlvtxvholzolragspjulatnalbmnatzkppekynuyqqciwgukcxyvzhubbhfyhixcjvgsirydtrsivhpclmwoxnzvfmrooiqbgqprzgsmpqnznbmktysjrevatmfslxfgglnsqnaiahhvfjiquzsfpldfldhmjislvekgqbulcywayiedqwmmkeyccsaffkatpxpdxpxbkezyskrxqzkvctyvopbgxioklmbeqnpkxcyoxaccloilylyvjkimkzncqdkfpeywfjocozhcvsxbzbumygcqltmkytvtcuksobabqhpiwpfgbufncfeegggyprkqhmbqtpgittxegwtewjjzptmptbudklgmcngyqmogjcccsrscjypbvjujhgqsckpunvpcmwqiyqaepkezfkpyhrygxvfanhsirjieyfggkubqdjweamhumtwqzqvmjhflhcyfbqelpdgnoqvcfagowvsrwctumcovdvolxyogqrhcpexnlrnonmyyuqanxmrvfedwimywitqbuaisksvgeimzbvzlzdukdupqknmeiclhzaaqqhhmjjyhnfkcoqvopajxlilaszeugwvuwnftkgpzqnqaikcqrymsysyjwwszporrhlzbmtwvcmuxautzcrjdbvxcwkxgmyspfrypmcnocebcimwccmqcnjnqtqxkmbdjjgxsomjgxwuhstzmcrnhszqwuaxevjbqrnxhutobkpmkmsrltbbaopqqytvidpczccgnclswltkjavisfrlhiwsdtguaevlddibizhcuwxpqozxhdbgnnewxbfindbsxcognyxmdyquiknesuivkzbbmwbcbfxasumqgpxrfccahuqqvejiuoplkmbuokxrmxntbpsreuemfoudcfjtmvairvpnqdvaadmswqakwedtiudwuuplzkuyeiaonmxxrfgowgvollnkymgsdwdllfltvhdwrrmelqfgtkitcadlnhrxaztifrmtrjtkfzfbhwjrveddthczkbwfmtykvjmkxdgllgjoriyueqgtphwkjiyuvtrenzxtjvraippntdhiatvxwnwjwfxiyefydxnkyclqpgdsrdecaupycthwaxhprkiumahmgeqwlhdvjrpjvdgmtroyykwnrsjbssabxrbzifjgkvtgfwszbkwgaomhkfztbhyrfbnyodsxkxzyduyumpfjdjyqkhoijwshecmdbjjwczgdwyorjapkfyxgujrhycrfngjnrpnyrbdogwypjshmistgczrbbzyawdhkayevubynuqbncnikbxkxevzzkjdtqvcxqqyagqmbxsrdesjrejwnrlbuxtgwicrelsnllngkrdyzekrquvbnkbzymztvzdtgciizmucdaghrszymssghhzufpwlkqgizlqvasyqpefsorgzueadreaoaiykfpmlhgdsbmsfblabvqnkiinijlvvvlvoefthrauqvvjfiwquvhyqjprmhjsvorgindyswhbtkjgqfrrqbluuvbrdpvptoimeikyzpnsnqxsetktzvcsclqsejrycfcvurfdnjgahnewpblrrdymtvachpxxtwwlplocjjunrzxcfmfifhdteqldudaikdmttpmtzkfsvrbscpaipcrkyavucpemqulzynujeyffmkzqyxfplablpenoqbcpkavczybsldrwagbgnyzcqcrbaczrbzlianoyyyqpsglahfoonlzzsqiwojtxwxhcjfwvbuyjqvbvdndraiizhfrbrirgaohdmhygumjeodbwbbcnuyudctpruodlsekoeeohqrmbiivofxtvvfoityjxkkoxwkhgvebbnzkefnqxdejetqkluyjotqoiwchdfnpnzovtwyopkowsjxgtyrwfsmfkrdrdqeuhdwppvwbioyvqndsnllldcrrplnijnznzhvxhredjakdjtuvmhknzmlegvssgkcmxbzpkjpproyvxupvbjyvliaygxwumtcjuykugyilyqotydxqslpbzarctbmpblxcnqelrkcmawesblpgerlcuakqlazrchyrarzswuorpymymuixilibsdsijwodyibybwekubbcobizormujmkpqpjcmrcpbsrfozrdkjgtczwtatfpjwsbnknimbdraokrqovjouipxnohiauxmholljxthlptmzfsqhslotmexhqfdpfbguzqbvfbatorphxkynlmxoimrxpztxeyltldvpryptdwenlgrfmcibpryiduhuormalnfquogcxalsczrguwdkzlysftsdlknslvkexpgskmarrjgwaxwfnwjphsilsojzlvtnoewfxhrcntzwmikvvvllsjhexpgbzypezhkhuegcbvqdmiyuumjlyeynrduboqwqniohvinxknytumuwtnsnuusbscqrbpaucrdedpdmqafaumdsfuwjfervrcubunprmmpxmyvaqghymhifufnypaevxknrdonviyvqhclngyflauzbofyueigedmoqrdofwjtnskdlbhamamgrcairegdhaiduvsnurtbyphjedoksiqoungvpzjlqneuhdckihgcougzkzgnxfmarfrzzxavgdnbcmegzpeoszbpfhhspunemcnqgspowglfvdoikvxglrhgxqyzghmvlvvzymeicomaemzodqddpcvkeixaofymmzbxdhsofaeygcneeffxuldwyskoisgtwjhotaneqmdvtxjtzpximmddvbvkwzlkzpjmacqvtwnzvazuelvuhnuxhyzutmtkzcbipbgatzokvxnyfiyimpwlwagwzqpkvoqsgobxljxdxfejkvcxkuaqxcxxyjgkwsjybtyxkngcbkgjvrzdrlvqmzrkmbwbzqsbzywcuubruenxvnfolafhxldvrwhzdfmocauellflmdocqqkqosnerzemcsejyoodiftkraqxppoyylwsaddktryluvzsnkukomunpjntgatzqyrngjvtpyyxvlvujmroklmlfprhzyjdrokdqmodiksexyzjateyounfrbcvohicrnhbqgrbrcgjmwtwpmnkhzciqroqbudslqsxrzkgjmrhkwuuokkodccqvvahxvtoovrdvvwmdbhhwyiziuxvajesbciqazkxlniwcyssttpgjfnsybsdiihcntglikwvwnsobonjxfadxpofuyascmdexxylotuegmtegcqlayuerdovcvbbtptyfwyakswmkjhyhdkfjtdlydnxsrnumeqisnayqokpwhsajtpbtbylfawjkuoljjwqtyifbgohjvcxedolpnlnmfkpgrbiimqdlinprqbxmwecexsnrumfvikkiugjzgqmlbreqjvpgvidockzejtrirdnsgvetpxifymovadobrpukwzdjfefwwifeeywzmvjmrtlohejvducaozuslhqlbzcdjhdomuzxstntcrszlizrwtplwdrralwxpzxglbuyaceahusgupmnkgotsaelvnieanhprqtgczswwomngirqmbvgwgxrsaxnfxhfqaduleuzarmlqvoqoxeisxhrxfffnkliydjogsghqnukedkmiuflijjijyaqqkinpydtpvsxmufjtvkcahqfzzvovkulkmlgvyfkyibjvukxlbkackimjdhpnuttwqpjjvxjyoqzwojcwcerstzsefreslppjxfbwsblyjvwzaqjnnphboyvzdspgmtwsutwaappptwchrwxnmdslzyrtvtqgmroxztboosrfhidmicifzedfnbtzxonshcrhsxulpykjuzmkgkbmjnarmeysmhpluloygldzwwhnqndtknhpntpnfewvkvqbiyezdudtnxyywlgxsegrjypifnoxxyemfueuvusjhfwqucskjvjgmyumyfojdoychmpemtydlfesnyjaownkyuenxppiudsbfshwgyzgcaofnbxheomimyptficohtktxstvdqbsrizgzwxjmkvvsekvjsgmuyjcefoeqfvssnskaflueavinhtmwltuzslapmcadzkqgeimynlqjrfpqowitybnexelibnyhvamidmlfmbtysfbphkddcwpbrjqmmwnplfmbdsasmafubmbqmvbimjlyuidxgtwslxbglkmfqqugubeaciotiyaaohfdkiyimalchtsodrjqcmyhzrnhcdddasezfvsjpxntqedztwajcqdxmehfrfzxyqbidqoxkgbsccjauxaeocmezfasiszpetwiaphahdnucihndwasvcewwizihqasnvmgxuvcltxkzutwmcecmtkvwkeiepzuwduzzhvvcckbljkcdrnrfevxgnghvuhsltwagkdzntylqradlfoxszltmqxyukxqkirmzledssynvpwhxhnlyfipufokdwahjcwypqjhnzlkxyhjxvmwovhvjqrvvuddhdxkhhjhvojzucqmndbquajmjswsxdlvhnsrkllqnhajtbcgozirvqbnfbrclqyyziayzpayfpqqpbgmygxojjlcfpqotpjydhigvpjvddajwkbcfearsqckhirrfdshwrksxgddebrnszylifyjknwlwfgzhnaxtymmzadekmiroxijossltuqlvkzrtdpuggifhkgguvocftabffcofbonkfesqiotlpvkzxjhgfpufkdqlsvdaslxxjdnfhmaevtuuehoksrwvotupcrwcdurdeinecmnkbtmjothvecqzjndzhcyhuwpsibhvutegzztvrxupizoantywrfoklihwclltuykogihwlcrdgqodeishfiuhqvxwyaonogrwskzylscwakismybslwfzjophixjgvqhlnbipueiccxbkbuqphdzzamsprygawbqbvzhnjqxfwmdneeocgnsrjkcmrafxjwiuegloppvtbbvftpbymsxluwrjijfefgsxtsmbsiuhmqwzipwrhivcbxycvreildfrbllwfwxrhzgiifrvkjsprtbnsazjaihmubpcgsmrqwykqwdutfoycdpvrqlxcdxacwrmuverljiiknesaqbomthhcfdfevwopgiaemkxywarvbezbauycavfnrwurautzrcdykcvupzzshmvesuadidfkyyxlxibbsanewiaiaepumsfystozmsyfcgmlpsufbazudjocfphkqekejhbbqambdtzwjlvcpcyimzbtcvzqqopmldaqjiczrjpitogugubzvikcrpfpyqfujxtfipvcvfhofeflphbuzoaiwunpbsngbkftskcpidtjizngyheimxbpsrdztkpaclsuyoojwepbvsilnsgmzrllbjworpwdhytavfufwsrxzhyqqwdwefiqawnufnywyopoiutqwrnmxoljcpmwkptpkdhguanzdaceyrebeabdhtlxgebswjdmbrmtolowshhcckuembqynamcalzedlexkpqmiyyrrawyczldzfveoaxscddgspglasrzvixqiehzxwctjgssmjoutxzgoyaobyqxcpjunbhqdeoudslaibdgwsbhawxulugfyrlhzcxgnbgppbqjeezwt", 1))
    }
}
