//
//  Main.swift
//  leetcode
//
//  Created by Henry on 2019/4/14.
//  Copyright © 2019 Henry. All rights reserved.
//

import Foundation

//TwoSumSolution.init().test()
//AddTwoNumbersSolution.init().test()
//LongestSubstringWithoutRepeatingCharactersSolution.init().test()
//PathSumSolution.init().test()
//PalindromeNumberSolution.init().test()
//ReverseIntegerSolution.init().test()
//RomanToIntegerSolution.init().test()
//LongestCommonPrefixSolution.init().test()
//MaximumDepthOfBinaryTreeSolution.init().test()
//AddBinarySolution.init().test()
//InvertBinaryTreeSolution.init().test()
//SqrtXSolution.init().test()
//AddDigitsSolution.init().test()
//PowerOfThreeSolution.init().test()
//ValidParenthesesSolution.init().test()
//PascalTriangleSolution.init().testGenerator()
//PascalTriangleSolution.init().testGetRow()
//PlusOneSolution.init().test()
//ClimbingStairsSolution.init().test()
//FibonacciNumberSolution.init().test()
//Base7Solution.init().test()
//AddToArrayFormOfIntegerSolution.init().test()
//BinaryNumberWithAlternatingBitsSolution.init().test()
//BinarySearchSolution.init().test()
//ArrangingCoinsSolution.init().test()
//ArrayPartitionSolution.init().testArrayPairSum()
//AddStringsSolution.init().test()
//CountPrimesSolution.init().test()
//ConvertSortedArrayToBinarySearchTreeSolution.init().test()
//BinaryPrefixDivisibleBy5Solution.init().test()
//oneBitAndTwoBitCharactersSolution.init().test()
//AssignCookiesSolution.init().test()
//AvailableCapturesForRookSolution.init().test()
//AverageOfLevelInBinaryTreeSolution.init().test()
//BackspaceStringCompareSolution.init().test()
//BalancedBinaryTreeSolution.init().test()
//BaseballGameSolution.init().test()
//BestTimeToBuyAndSellStockSolution.init().testOnce()
//BestTimeToBuyAndSellStockSolution.init().testMultiple()
//BinaryGapSolution.init().test()
//BinaryTreeLevelOrderTraversalSolution.init().test()
//BinaryTreePathsSolution.init().test()
//RemoveDuplicatesFromSortedArraySolution.init().test()
//MergeTwoSortedListsSolution.init().test()
//RemoveElementSolution.init().test()
//ImplementStrStrSolution.init().test()
//SearchInsertPositionSolution.init().test()
//CountAndSaySolution.init().test()
//MaximumSubarraySolution.init().test()
//LengthOfLastWordSolution.init().test()
//RemoveDuplicatesFromSortedListSolution.init().test()
//MergeSortedArraySolution.init().test()
//SameTreeSolution.init().test()
//SymmetricTreeSolution.init().test()
//MinStack.init().test()
ExcelSheetColumnNumberSolution.init().test()
